'''so we learn the "kag gik" rules...
Now we want to see the proportion of illegal vs. legal errors
that are generated by this hypothesis space.'''

illegals = ['n i h', 'N i n', 'N a h', 'f a h', 'f i h', 'g i n', 'g i f', 'k a n', 'N i f', 's i k', 'm i h', 'k a f', 's i h', 'N a f', 'g i m', 'n a g', 'k a m', 'n i k', 'g i h', 'N i m', 'N a m', 'm a h', 'N a g', 'N a n', 'N i s', 's a h', 'N i k', 's a g', 'n a h', 'g i s', 'm i k', 'N a s', 'k a h', 'm a g', 'k a s', 'k a g', 'f i k', 'N i h']
